language: groovy
 
jdk:
  - oraclejdk7

before_install:
  - rm -rf ~/.gvm
  - curl -s get.gvmtool.net > ~/install_gvm.sh
  - chmod 775 ~/install_gvm.sh
  - ~/install_gvm.sh
  - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
  - source ~/.gvm/bin/gvm-init.sh
  - gvm install grails $GRAILS_VERSION || true
  - chmod 775 ./travis-build.sh
 
branches:
  only:
  - master

before_script:
  - rm -rf target

script: ./travis-build.sh

env:
  matrix:
    - GRAILS_VERSION=3.0.2
